<?php
    return [
        'religions'  => [
            'Islam' => 'Islam',
            'Christian' => 'Christian',
            'Catholic' => 'Chatolic',
            'Hindu' => 'Hindu',
            'Budha' => 'Budha',
            'Konghucu' => 'Konghucu'
        ],
        'maritalStatuses' => [
            'Single' => 'Single',
            'Married' => 'Married',
            'Single Parent' => 'Single Parent',
        ],
        'typeOfContractPrint' => [
            'Contract With Penalty' => 'Contract With Penalty',
            'Contract Expat(chef)' => 'Contract Expat(chef)'
        ],
        'previousEmploymentOptions' => [
            'New Hired' => 'New Hired',
            'Transferred from OI Batch I' => 'Transferred from OI Batch I',
            'Transferred from OI Batch II' => 'Transferred from OI Batch II',
            'Transferred from OI Batch III' => 'Transferred from OI Batch III',
            'Transferred from HTI to DGE' => 'Transferred from HTI to DGE',
            'Transferred from OI Batch IV' => 'Transferred from OI Batch IV',
            'Transferred from OI Batch V' => 'Transferred from OI Batch V',
            'Transferred from DGE Project NSN' => 'Transferred from DGE Project NSN',
            'Transferred from IMSI Project NSN' => 'Transferred from IMSI Project NSN',
            'Transferred from HTI Batch VI' => 'Transferred from HTI Batch VI',
            'New Hired After 18 November 2013' => 'New Hired After 18 November 2013',
            'Re Arrangement ex HTI' => 'Re Arrangement ex HTI',
            'Transferred from DYKA to DGE' => 'Transferred from DYKA to DGE',
            'Transferred from HS to ARP' => 'Transferred from HS to ARP',
            'Transferred from DCPE to ARP' => 'Transferred from DCPE to ARP',
        ],
        'furtherStatusOptions' => [
            'Cancel Contract' => 'Cancel Contract', 
            'Freelance' => 'Freelance', 
            'Not Extend' => 'Not Extend', 
            'Resign' => 'Resign', 
            'Terminate' => 'Terminate', 
            'Terminate Black List' => 'Terminate Black List', 
            'Transfer to HTI' => 'Transfer to HTI', 
            'Transfer to Other Company' => 'Transfer to Other Company', 
            'Move To New ID After 18 November 2013' => 'Move To New ID After 18 November 2013', 
            'Passed away' => 'Passed away', 
            'Convert to ARP' => 'Convert to ARP', 
        ],
        'employeeStatusOptions' => [
            'Contract' => 'Contract',
            'Permanent' => 'Permanent'
        ],
        'signInBonusTypeOptions' => [
            'Continue' => 'Continue', 
            'First Contract-End of Contract' => 'First Contract-End of Contract', 
            'First Contract' => 'First Contract', 
            'End Of Contract' => 'End Of Contract', 
        ],
        'thrOptions' => [
            'Full' => 'Full', 
            'Prorate' => 'Prorate', 
            'No THR' => 'No THR', 
        ],
        'taxTypeOptions' => [
            'Net' => 'Net', 
            'Gross Up' => 'Gross Up', 
            'Tenaga Ahli' => 'Tenaga Ahli', 
        ],
        'categoryOptions' => [
            'DCPE' => 'DCPE', 
            'ARP' => 'ARP', 
            'C' => 'C', 
        ],
        'advanceVia' => [
            'Cash' => 'Cash', 
            'Deutche Bank' => 'Deutche Bank',
            'eMFTS Niaga' => 'eMFTS Niaga'
        ],
        'banks' => [
              "008" => "Bank Mandiri",
              "009" => "Bank Negara Indonesia (BNI)",
              "010" => "Bank Rakyat Indonesia (BRI)",
              "011" => "Bank Tabungan Negara (BTN)",
              "012" => "Bank Danamon",
              "013" => "Bank Central Asia (BCA)",
              "014" => "Bank CIMB Niaga",
              "015" => "Bank Panin",
              "016" => "Bank Permata",
              "017" => "Bank OCBC NISP",
              "018" => "Bank UOB Indonesia",
              "019" => "Bank Citibank Indonesia",
              "020" => "Bank HSBC Indonesia",
              "021" => "Bank Standard Chartered Indonesia",
              "022" => "Bank ABN AMRO Indonesia",
              "023" => "Bank ANZ Indonesia",
              "024" => "Bank Commonwealth Indonesia",
              "025" => "Bank DBS Indonesia",
              "026" => "Bank Maybank Indonesia",
              "027" => "Bank Mega",
              "028" => "Bank Sinarmas",
              "029" => "Bank MNC Internasional",
              "030" => "Bank Bukopin",
              "031" => "Bank Muamalat Indonesia",
              "032" => "Bank Syariah Mandiri",
              "033" => "Bank BNI Syariah",
              "034" => "Bank BRI Syariah",
              "035" => "Bank BCA Syariah",
              "036" => "Bank Danamon Syariah",
              "037" => "Bank CIMB Niaga Syariah",
              "038" => "Bank Panin Syariah",
              "039" => "Bank Permata Syariah",
              "040" => "Bank OCBC NISP Syariah",
              "041" => "Bank UOB Indonesia Syariah",
              "042" => "Bank Citibank Indonesia Syariah",
              "043" => "Bank HSBC Indonesia Syariah",
              "044" => "Bank Standard Chartered Indonesia Syariah",
              "045" => "Bank ABN AMRO Indonesia Syariah",
              "046" => "Bank ANZ Indonesia Syariah",
              "047" => "Bank Commonwealth Indonesia Syariah",
              "048" => "Bank DBS Indonesia Syariah",
              "049" => "Bank Maybank Indonesia Syariah",
              "050" => "Bank Mega Syariah",
              "051" => "Bank Sinarmas Syariah",
              "052" => "Bank MNC Internasional Syariah",
              "053" => "Bank Bukopin Syariah"
        ],
        'hideRelationManagerOnViewContract' => false,
        'taxStatuses' => [
            'TK0' => 'TK0',
            'TK1' => 'TK1',
            'TK2' => 'TK2',
            'TK3' => 'TK3',
            'K0' => 'K0',
            'K1' => 'K1',
            'K2' => 'K2',
            'K3' => 'K3',
        ],
        'terStatus' => [
            'TK0' => 'TER A',
            'TK1' => 'TER A',
            'TK2' => 'TER B',
            'TK3' => 'TER B',
            'K0' => 'TER A',
            'K1' => 'TER B',
            'K2' => 'TER B',
            'K3' => 'TER C',
        ],
        'bpjsKesehatanAmount' => 480000,
        'insuranceAmount' => 180000,
        'max_bpjs_kesehatan' => 12000000,
        'max_bpjs_pension' => 9559000
    ];